### ISSUE TITLE
Method App\\Nova\\Templates\\Formations::forceFill does not exist

### ISSUE THREAD

**Issue by ikramooe** [whitecube/nova-page#102]
as the title says 
i'm using nova 4

**Comment by GarethSomers** [comment]
Any update on this ?

**Comment by GarethSomers** [comment]
This issue is still happening with Nova Page, I assume it's fixed within Nova Flexible Content though.

**Comment by voidgraphics** [comment]
@GarethSomers indeed! I've just contacted the Nova team to get us a package-dev license so I can take a look at this. Apologies for the wait.

**Comment by GarethSomers** [comment]
Hey @voidgraphics appreciate all your efforts. If there's any updates please let me know.
