### ISSUE TITLE
Ability to change the use rmodel namespace in NovaPagePolicy

### ISSUE THREAD

**Issue by wimurk** [whitecube/nova-page#12]
Like the title says. in the `NovaPagePolicy` the model `App\User` is included. THis gives an error when the model is located somewhere else. 

A good way would be like the `User` resource where the user model is a config item.

**Comment by Nyratas** [comment]
Hi @wimurk,

We faced this issue in #10 and resolved it by removing the default Policy. It will be shipped in the next release. Meanwhile you can use `dev-master` and define your own Policy gates on the `nova-page` resource.

Thanks for your feedback! :)

**Comment by wimurk** [comment]
@Nyratas thanks for the quick response. Great package btw
