### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ChrisSFR** [whitecube/nova-page#20]
In the Documentation and on novapackages we can see Text Fields with the localization feature.

I saw you removed the ability to load templates with the locale parameter. What was the reason and what would be the best way to enable localization.
Making multiple Templates for every language?

**Comment by Nyratas** [comment]
Hi @ChrisSFR,

It depends on which package you use for translating the fields. If the package claims to store translations in a json column, then it will simply work as expected with our package, because translated field values are stored in the same json file.

We have several websites running with this package & using translated fields and have not encountered any issues yet.

Which translated fields package do you use?

**Comment by voidgraphics** [comment]
To add onto the previous answer, we felt it was a bad decision to force a particular way to handle translated data, so we removed it and if you need it, you can choose how to make it work yourself. We aim to be as little opinionated as possible.

If you're curious about how we do it, we use [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) on both our models and our Nova Page templates to define which fields contain translated data.

Then, we use [mrmonat/nova-translatable](https://packagist.org/packages/mrmonat/nova-translatable) to make that translatable data editable in Nova. Note that Spatie themselves have made a similar package, but we found mrmonat's UI was better for our needs.

**Comment by ChrisSFR** [comment]
Thank you for your quick answer. Thats exactly what I was searching for.
Btw thanks for this great package!

**Comment by fede91it** [comment]
> To add onto the previous answer, we felt it was a bad decision to force a particular way to handle translated data, so we removed it and if you need it, you can choose how to make it work yourself. We aim to be as little opinionated as possible.
> 
> If you're curious about how we do it, we use [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) on both our models and our Nova Page templates to define which fields contain translated data.
> 
> Then, we use [mrmonat/nova-translatable](https://packagist.org/packages/mrmonat/nova-translatable) to make that translatable data editable in Nova. Note that Spatie themselves have made a similar package, but we found mrmonat's UI was better for our needs.
> 
> Also I am closing this since it is not an issue and rather a question.

spatie/nova-translatable required the HasTranslations trait to be added to the model behind the nova resource (in that case the Template), so at the saving of the template we got a Method App\Nova\Templates\Home::setTranslation does not exist. error.

How do you handled the spatie's package here on nova page?

**Comment by voidgraphics** [comment]
The `setTranslation` method is a part of the `HasTranslations` trait from the spatie/laravel-translatable which should indeed be applied on the template class. If it complains that the method does not exist, either you did not apply the trait on your template, or there is a problem with the trait itself.

**Comment by fede91it** [comment]
HasTranslations must be applied to the Model referenced by a Nova Resource so where is that Model? No way to place a fake setTranslations method, the request doesn't get the values submitted with the form

**Comment by voidgraphics** [comment]
```php
<?php 

namespace App\Nova\Templates;

class Home extends Template {

    use HasTranslations;

    // ...
}

```

No need for a fake `setTranslations` method, it's part of the `HasTranslations` trait.

**Comment by fede91it** [comment]
No man

HasTranslations seguire an eloquent model instance

**Comment by voidgraphics** [comment]
There is no eloquent model. There is a template class instead. I have used the HasTranslation trait exactly the way I showed you before and it works fine.

**Comment by fede91it** [comment]
Please provide a full example with fields and db. If I use HasTranslations don't work

**Comment by fede91it** [comment]
I don't know what magic you are doing, but I just updated spatie/nova-translatable to the latest version 4.2.1, and as soon as I open the page editing page I get this error:

`Argument 1 passed to Spatie\NovaTranslatable\Translatable::Spatie\NovaTranslatable\{closure}() must be of the type string, array given, called in D:\Projects\laravel-zona30\vendor\laravel\framework\srcIlluminate\Support\Collection.php on line 494`

E questo è la mia classe Template:

```php
<?php

namespace App\Nova\Templates;

use Illuminate\Http\Request;
use Laravel\Nova\Fields\Text;
use Spatie\NovaTranslatable\Translatable;
use Spatie\Translatable\HasTranslations;
use Whitecube\NovaPage\Pages\Template;

class Home extends Template
{
    use HasTranslations;

    /**
     * Get the fields displayed by the resource.
     *
     * @param Request $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            Translatable::make([
                Text::make('Foobar'),
            ]),
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param Request $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }
}
```

**Comment by gldrenthe89** [comment]
> To add onto the previous answer, we felt it was a bad decision to force a particular way to handle translated data, so we removed it and if you need it, you can choose how to make it work yourself. We aim to be as little opinionated as possible.
> 
> If you're curious about how we do it, we use [spatie/laravel-translatable](https://github.com/spatie/laravel-translatable) on both our models and our Nova Page templates to define which fields contain translated data.
> 
> Then, we use [mrmonat/nova-translatable](https://packagist.org/packages/mrmonat/nova-translatable) to make that translatable data editable in Nova. Note that Spatie themselves have made a similar package, but we found mrmonat's UI was better for our needs.
> 
> Also I am closing this since it is not an issue and rather a question.

Do you stil get this to work? cause i am not. what are you doing different?

**Comment by f-liva** [comment]
That's what I did.

```php
/**
     * Get the fields displayed by the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return array
     */
    public function fields(Request $request)
    {
        $locales = LaravelLocalization::getLocalesOrder();

        $fields = [];

        foreach ($locales as $localeCode => $properties) {
            $fields[] = Text::make("Text", "text_{$localeCode}");
        }

        return $fields;
    }
```

**Comment by gldrenthe89** [comment]
thanks that worked like a charm

**Comment by nidhalkratos** [comment]
Hi, I have read this thread, and even though It is called "Localization" everyone was talking about translation, which just one part of localization. When we say localization, it is not just the language. For example, some page section may be completely hidden for some countries, so sections are country specific, ... For example, if you visit apple's website from the US or from Europe, you will not see the same sections visible. For example, you will see the Apple Vision Pro product section only when you visit the site from the US. 
Now, back to our discussion here, It makes more sense if we made it possible to make some pages locale-specific. 
We can achieve that by adding a new 'locale' field in the 'pages' table. And then, we let the user specify it from Nova. 
And then, when loading the page, we can load the correct page based on the locale user's selected locale. With the help true localization packages such as https://github.com/mcamara/laravel-localization we could achieve full localization. 
This of course in addition to all the things said about the translation in the current thread.
We can make this change in a way that it can be optionally enabled in the config file to give more flexibility to people that are interested in true localization. 
I can make the necessary changes, and create a pull request, the question is, @voidgraphics are you still open to accept pull requests for this package ?
