### ISSUE TITLE
Installation not working on Laravel 5.8 & Nova 2

### ISSUE THREAD

**Issue by raphcollective** [whitecube/nova-page#21]
Hi, thank you so much for the great package.

I wasn't able to install it correctly on Laravel 5.8 and Nova 2.0.0, the package:discover command returns this error after doing a composer update:

`In Container.php line 794: Class blade.compiler does not exist`

I tried digging into it but couldn't find anything relevant. In the meantime I'll use a 5.7 environment.

Thanks again!

**Comment by Nyratas** [comment]
Hi @raphcollective,

We'll take a few minutes to upgrade the package for Laravel 5.8 and Nova 2.0 later this week. I'll keep you updated via this thread.

**Comment by raphcollective** [comment]
@Nyratas thank you!

**Comment by estaticfear** [comment]
I'm getting this issue on nova 2 and laravel 5.8 too, waiting for next update.
Thanks you so much, this plugin is so amazing.

**Comment by voidgraphics** [comment]
Fixed in b080897303b59ce4d6e6f0d13728fb27781906db

I will publish a new release (v0.1.8) as soon as I get a few other issues fixed.

**Comment by jonarribasmateo** [comment]
We can't wait :))

**Comment by voidgraphics** [comment]
Nevermind my previous message, the version number is [v0.2.0](https://github.com/whitecube/nova-page/releases/tag/v0.2.0)

Could you please check and tell me if everything is okay on your end? I'm seeing some issues on Travis but it works fine locally for me.

Thank you!

**Comment by jonarribasmateo** [comment]
It works!!
