### ISSUE TITLE
Values get cached when using the blade directive

### ISSUE THREAD

**Issue by raphcollective** [whitecube/nova-page#29]
Not sure if intentional, maybe the doc should specify it but the values are cached when using the `@get` directive which means one has to run a view:clear every time they update a page on nova.

`<p>@get('phone')</p>` will be cached like this `<p>+1234567890</p>`
But `<p>{{ Page::get('phone') }}</p>` will be `<p><?php echo e(Page::get('Footer','phone')); ?></p>`

Is that the intended behavior? If so maybe the docs could be updated to reflect that choice a bit more.

**Comment by voidgraphics** [comment]
Hi, I can confirm that this is **not** intended behavior. In fact I have noticed this myself but I have not had time to investigate it.
