### ISSUE TITLE
Remove default Page Title?

### ISSUE THREAD

**Issue by milewski** [whitecube/nova-page#30]
Hi is it possible to remove these 2 fields from the default page? i need the title to be translatable but i don't see where i can remove/edit that

![image](https://user-images.githubusercontent.com/2874967/55684464-4f6f7780-597d-11e9-9863-2bdce21863f3.png)

**Comment by voidgraphics** [comment]
Hello @milewski, at the moment it is not possible to remove these default fields. Please note that the "Page title" field shown there is an internal field for our package, it's what we use to show the name of the page on the "Pages" list.

If you need to have a translated page title to display in your front-end, you may absolutely add a separate field for that.

If you do however need to have a translated page title within Nova itself, that is not supported at the moment, but if we get enough requests for it we may consider it in the future.

**Comment by adrian-schnell** [comment]
I'd love to translate all the nova be field names as well

**Comment by GarethSomers** [comment]
Anyone finding this the PR https://github.com/whitecube/nova-page/pull/45 will allow you to extend the PageResource (and implement your own fields).
