### ISSUE TITLE
Edit button disappear when Panel is used.

### ISSUE THREAD

**Issue by m-a-k-o** [whitecube/nova-page#32]
Without panel:
![image](https://user-images.githubusercontent.com/6873535/56657284-ed5e8400-6697-11e9-8fc4-372bb447744f.png)

With Panel:
![image](https://user-images.githubusercontent.com/6873535/56657265-dfa8fe80-6697-11e9-97e9-8a2fe077dfb6.png)

With Panels I'm not able to edit pages from Detail page only form index.

Thank you.

**Comment by voidgraphics** [comment]
Can confirm. Thanks for the report.

**Comment by OliverZiegler** [comment]
any progress on this?
