### ISSUE TITLE
Error when saving image using nova filemanager

### ISSUE THREAD

**Issue by yassir3wad** [whitecube/nova-page#41]
`
Symfony\Component\Debug\Exception\FatalThrowableError
vendor\whitecube\nova-page\src\Pages\StaticResource.php
line: 52
Argument 1 passed to Whitecube\NovaPage\Pages\StaticResource::__construct() must be an instance of Whitecube\NovaPage\Pages\Template, instance of Whitecube\NovaPage\Pages\Manager given, called in vendor\laravel\nova\src\Http\Requests\InteractsWithResources.php on line 65
`

`
    public function fields(Request $request)
    {
        return [
            FilemanagerField::make('Cover Image')
                ->help("max file size 4M")
                ->rules("required", new CheckImage(4))
                ->folder("pages")
                ->displayAsImage()
                ->hideFromIndex()

        ];
    }
`

laravel version: 5.8.30
nova version: 2.0.9
nova-page version:  0.2.3
infinety-es/nova-filemanager version: 2.3

**Comment by Nyratas** [comment]
Hi @yassir3wad,

Is this issue still around in Nova 2.4.0?

Thanks

**Comment by yassir3wad** [comment]
No, Thanks @Nyratas

**Comment by amidesfahani** [comment]
in nova 3.12.1
