### ISSUE TITLE
When saving new option template, it required a "title"

### ISSUE THREAD

**Issue by stufarquhar** [whitecube/nova-page#49]
When saving a new option, it requires a "title". Nothing is saving to the DB table resulting in a Not null error.

v^0.2.3

**Comment by Nyratas** [comment]
Hi @stufarquhar,

Could you be more specific? Does the form show a validation error or do you get an exception when saving options?

I understand you're using the package with the database source. Does your `static_pages` table have `nullable` title (it should be if you used our latest migration)?

**Comment by stufarquhar** [comment]
Hi @Nyratas, yes I am using this as a database source. It not seen to update the table with a migration. I manually changed the table to nullable and this seemed to work. 

Regarding your first question, it threw an exception error a typical not null! All seems to be working well not. FYI, great package by the way!

**Comment by Nyratas** [comment]
Hi @stufarquhar,

I have to agree we didn't publish a new migration for this tiny change, but as you can see, [the migration file](https://github.com/whitecube/nova-page/blob/master/database/migrations/2019_00_00_000000_create_static_pages_table.php#L20) now contains a `nullable` statement on the `title` attribute. Your manual change has the same effect as running the latest migration. I'm closing this issue now.

Thanks for the kind words and for bringing this to our attention!

**Comment by stuartcusackie** [comment]
I am also seeing this problem now 4 years later on Nova 4. I will open a new issue.
