### ISSUE TITLE
Update docs to registering options

### ISSUE THREAD

**Issue by f-liva** [whitecube/nova-page#54]
From AppServiceProvider

`$pages->registerOption('general', GeneralOptions::class);` don't works
`$pages->register('option', 'general', GeneralOptions::class);` it works

**Comment by voidgraphics** [comment]
Took me a while but I finally got to it. Thank you very much for the report.

**Comment by lmatab** [comment]
How can we access this page information in a controller?, I need to use a select field to set the currency in the system.

**Comment by voidgraphics** [comment]
You can use the Page facade: https://whitecube.github.io/nova-page/#/?id=useful-facade-methods

More specifically the `Page::option()` method.

**Comment by voidgraphics** [comment]
You can use the Page facade: https://whitecube.github.io/nova-page/#/?id=useful-facade-methods

More specifically the `Page::option()` method.

**Comment by lmatab** [comment]
Thanks

I tried to use it but it shows an error:

"Class 'Page' not found"

**Comment by voidgraphics** [comment]
```php
use \Page;

// or

use Whitecube\NovaPage\NovaPageFacade as Page;
```
