### ISSUE TITLE
New pages won't show up.

### ISSUE THREAD

**Issue by margaritacoco** [whitecube/nova-page#57]
It's been awhile since i've used Nova, updated from 2.0.6 to 2.9.4 this morning.

Laravel: 5.8
Laravel Nova: 2.9.4
Laravel Nova-Page: 0.2.3

Somehow, the new pages(none are existant for the moment) are not showing up when I created one through _Php _artisan__.

Is there some change? I've followed the doc and i'm storing in the database. My table "static_pages" is still there although it's empty from my previous usage when I was on 2.0.6.

**Small update:** The new pages are just not getting added to the Database, at all. Files are being created, but not added to the database(Yes, my database config is working.)

**2nd update:** Completely removed any refererences of the package in my whole Laravel project. Did a fresh install of the package, still won't add to the Database. I can confirm, that Nova has access to my Database content. So it's not the connection or database config.

Any clues?

**Comment by margaritacoco** [comment]
FIX:

Honestly, there is no fix. I did a fresh install, and somehow it worked. I guess it's a conflict of when I updated my Nova and the other packages.

**Comment by michael-presentcompany** [comment]
I am experiencing the same issue as above, but a more recent version of Laravel/Nova:

Laravel: 8.6.0
Laravel Nova: 3.10.0
Laravel Nova-Page: 0.2.5

I can manually register options in the AppServiceProvider, but Pages wont load into Nova?
