### ISSUE TITLE
@extends('layout') not found

### ISSUE THREAD

**Issue by dotWaldemar** [whitecube/nova-page#58]
```
@extends('layout')

@section('pageName', 'some pageName')

@section('content')
    <h1>Section Content</h1>
@endsection
```

local.ERROR: View [layout] not found.
I try @extends('nova::layout') but have the same error `nova` layout  not found
Here is my controller
```
    public function show(Request $request, Manager $page, Template $template)
    {
        $page->loadForRoute($request->route());

        return view('pages.about');
    }
```

**Comment by voidgraphics** [comment]
Hi @dotWaldemar, I doubt that this error has anything to do with this package.

Is there maybe a typo in your `layout.blade.php` file name?

**Comment by dotWaldemar** [comment]
I want to expand the basic template from nova

**Comment by voidgraphics** [comment]
[Here's what I found.](https://laracasts.com/discuss/channels/nova/how-can-i-overwrite-laravel-novas-layout-view)

I think you are confused about what this package does. It is meant to make your website's pages editable, it does not allow you to customise nova itself.

**Comment by dotWaldemar** [comment]
How can I extend the base nova template?

```
@extends('layout') --- Extend base nova template

@section('pageName', 'Some title')

@section('content')
    Some content
@endsection
```

**Comment by voidgraphics** [comment]
What is the "base nova template"?

**Comment by dotWaldemar** [comment]
I want change just a content
![image](https://user-images.githubusercontent.com/25832802/74228448-1b659100-4cc9-11ea-86a6-be2749d92bf4.png)

**Comment by voidgraphics** [comment]
Are you trying to make [a tool](https://nova.laravel.com/docs/2.0/customization/tools.html#overview)?

**Comment by dotWaldemar** [comment]
the tool does not suit me
