### ISSUE TITLE
Undefined index: model

### ISSUE THREAD

**Issue by rabichawila** [whitecube/nova-page#62]
Helping someone with their project and we're facing this error.
Anyone who know what we might be missing?..

![Screenshot from 2020-04-04 13-31-31](https://user-images.githubusercontent.com/37574136/78444501-3c1ee700-7679-11ea-8602-ef0b16672f42.png)

**Comment by Nyratas** [comment]
Hi @rabichawila,

This seems to be related to the database data source usage. Did you [take a look at the docs](https://whitecube.github.io/nova-page/#/?id=using-the-database-as-the-data-source)? Let me know if you find something.

**Comment by rabichawila** [comment]
I have managed to suppress the error with this :

`config/novapage.php `

```
        'database' => [
            'table_name' => 'static_pages',
            'model' => 'App\\Models\\StaticPage',
        ],
```

Thanks.
