### ISSUE TITLE
NaN-NaN in Nova pagination

### ISSUE THREAD

**Issue by yammycode** [whitecube/nova-page#63]
Hi!
I noticed a problem. Laravel 7.10, Nova 3.5.0.
NaN-NaN of -COUNT- in pagination line.
See here: [https://prnt.sc/sf3n2b](https://prnt.sc/sf3n2b)

**Comment by amidesfahani** [comment]
Still exists

**Comment by AlexanderSix** [comment]
Still having this issue:

- Nova 3.14.0
- Laravel 8.12.0

![image](https://user-images.githubusercontent.com/11881203/97745631-89ecb800-1abf-11eb-915c-7d34286caf68.png)
