### ISSUE TITLE
Argument 1 Passed must be an Instance of

### ISSUE THREAD

**Issue by amidesfahani** [whitecube/nova-page#70]
![image](https://user-images.githubusercontent.com/61671721/94463546-faa36a80-01c9-11eb-9c72-5cbc5f9b2614.png)

When I click "Edit" one page then click on "Pages" in Sidebar this error shows

Nova 3
Laravel 8

**Comment by BenSampo** [comment]
For me this was caused by route caching as per #64. The solution is to disable route caching until there's a fix.
