### ISSUE TITLE
Deleting Images in Flexible Content Field

### ISSUE THREAD

**Issue by temp1029** [whitecube/nova-page#74]
I think this is a cross-package issue with [nova-flexible-content](https://github.com/whitecube/nova-flexible-content). When I try to delete an image from flexible content in a nova-page resource I am seeing a 404 error.

I've traced the issue down to [this line](https://github.com/whitecube/nova-page/blob/b1264c3d4717565dcc556a408b350e555c3b8a9e/src/Http/Controllers/ResourceFieldDestroyController.php#L32) not returning a resource (i.e. it's set to null) and then the subsequent instance of check failing. I believe the issue is with the value of 'field' passed as the last part of the URL.

Deleting images on a nova-page resource outside of flexible content field works as expected. I haven't had the chance to try deleting an image inside a flexible content field on a regular nova resource.

**Comment by Nyratas** [comment]
Hi @temp1029, this is definitely [an issue with Flexible Content](https://github.com/whitecube/nova-flexible-content/issues/1).
