### ISSUE TITLE
FR: Hide options from sidebar

### ISSUE THREAD

**Issue by stuartcusackie** [whitecube/nova-page#79]
Great package! Really solves a lot of problems for me.

Just wondering if there's an easy way to disable 'Options' in the sidebar. I won't be needing them for my current project and I would prefer to remove the clutter.

If not, can we get an option in the config file for this?

Thanks for all your work.

**Comment by voidgraphics** [comment]
Not possible yet, but would be a good feature to have. We would certainly accept a PR for this.
