### ISSUE TITLE
Nova 4 Support

### ISSUE THREAD

**Issue by chrisvasey** [whitecube/nova-page#87]
Hello!

I wondered if there are any plans to add Nova 4 support for this package?
I loved using it in Nova 2 a while ago.

If not, I am happy to have a crack at creating a PR, didn't want to duplicate any work.

Chris

**Comment by toonvandenbos** [comment]
Hi @chrisvasey,

Yes, I know @FlorenceRandaxhe started working on a Nova 4 update this week, but I don't know how much has been done at this point. Maybe you could give her a hand when she'll push the PR ? Thanks !

**Comment by toonvandenbos** [comment]
Hi @chrisvasey,

A [new branch](https://github.com/whitecube/nova-page/tree/nova-4) has been created by @FlorenceRandaxhe, but she doesn't have much time right now due to some deadlines on our side. If you have the opportunity to take a look at it, that would be great.

**Comment by MannikJ** [comment]
Is there any progress on this? 

I've tried to use the [nova-4 branch](https://github.com/whitecube/nova-page/tree/nova-4) within a laravel v9 app but I'm getting some errors. I have not yet had the time to dive into the code base too deeply, but maybe we can join forces and make this work again.

I've already forked the package and fixed the failing tests (locally) in the nova-4 branch by passing in instances of ` Laravel\Nova\Http\Requests\NovaRequest`, but there are still other issues. 
 
For example when I activate the tool, it throws a `Whitecube\NovaPage\Exceptions\TemplateNotFoundException` for every resource details I try to open.

**Comment by ants4t** [comment]
Will this update support laravel 8 as well as 9? Waiting to upgrade to Nova 4 from 3 but rely on Nova Page, and we arent ready to upgrade to laravel 9.

**Comment by toonvandenbos** [comment]
@ants4t Yes it will. We're trying to make time for this in the coming days.

@MannikJ thanks, we'll definitely take a look at your work. If you have some progress to share since you posted, do not hesitate to create a PR.

**Comment by toonvandenbos** [comment]
**Update:** our nova-4 branch has been merged into master and has been released under tag v0.3.0.
