### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'resource')

### ISSUE THREAD

**Issue by aliwesome** [whitecube/nova-page#89]
I'm using this package with a fresh installation of `Laravel Nova 4.11.1`.

This is the console error when I open up pages resource:
`TypeError: Cannot read properties of undefined (reading 'resource')`

This would show no pages even when I generate templates.

**Comment by toonvandenbos** [comment]
Hi @aliwesome, Did you publish the latest assets ?

**Comment by toonvandenbos** [comment]
Good point. I'll add an extra check before the list is displayed too.
