### ISSUE TITLE
Bug with Heading field

### ISSUE THREAD

**Issue by voidgraphics** [whitecube/nova-page#9]
When using the new nova Heading field, the package tries to load a value for it, but does not find one since the Heading field does not have a key.

A workaround to this would be to not throw an exception when the package tries to get a value without a key, just return nothing instead.

<img width="1171" alt="capture d ecran 2019-02-01 a 11 05 26" src="https://user-images.githubusercontent.com/9298484/52116477-83db5600-2611-11e9-9601-fba5ecbfae0d.png">

**Comment by Nyratas** [comment]
I just found another issue with the Heading field, but I'm not sure if it's linked to the package.

When trying to save a Page having a Heading in its fields, Nova's JS will log an error (even before the update request is sent out to the backend):

> Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
![image](https://user-images.githubusercontent.com/5635557/52348592-fb9bed00-2a24-11e9-85e9-f76a5ffe060e.png)

As I said, this could be an issue with Laravel Nova itself.

**Comment by voidgraphics** [comment]
Closing as this was a bug with one of our websites and not this package
