### ISSUE TITLE
Class Whitecube\NovaPage\NovaPageTool contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

### ISSUE THREAD

**Issue by abasakre** [whitecube/nova-page#91]
I have problem
this error

Class Whitecube\NovaPage\NovaPageTool contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Laravel\Nova\Tool::menu)

**Comment by toonvandenbos** [comment]
The remaining method [is implemented](https://github.com/whitecube/nova-page/blob/778f42e7494878e73333a492423623d9312ac06e/src/NovaPageTool.php#L31). I think you have an issue unrelated to this package.
