### ISSUE TITLE
Error deleting a file

### ISSUE THREAD

**Issue by arhitektorr** [whitecube/nova-page#92]
When deleting and uploading a new file, such an error occurs. I can't understand why the error occurs. Everything worked on the local. I ask you to help solve the issue and suggest what it might be

Whitecube\NovaPage\Pages\StaticResource::__construct(): Argument #1 ($resource) must be of type Whitecube\NovaPage\Pages\Template, Whitecube\NovaPage\Pages\Manager given, called in /var/www/www-root/data/www/site.com/vendor/laravel/nova/src/Http/Requests/InteractsWithResources.php on line 69

![444](https://user-images.githubusercontent.com/63448959/183587421-4c28f693-b9b4-4f36-8594-63aa4a5b1b5f.JPG)

**Comment by AbdullahGhanem** [comment]
up
