### ISSUE TITLE
Can this be used for multiple page layouts?

### ISSUE THREAD

**Issue by HeadStudios** [whitecube/nova-page#97]
If I have a BDM landing page for multiple users - can i use this extension for users to login and modify their pages? If so can you direct me to the part of the documentation that makes this possible? Thank you!

**Comment by toonvandenbos** [comment]
Hi @HeadStudios,

I'm not sure I understand your case, but this package only adds page resource edition features to Laravel Nova. I'd suggest you take a look at its implementation and decide if it suits your use case :)

**Comment by HeadStudios** [comment]
Hi,

Thanks for response - let me explain further my use case if that's okay and you can let me know if this suits.

I have landing pages setup for various users in my app - I would like them to modify their own landing pages using Nova page extension when they login. Is this possible?

**Comment by toonvandenbos** [comment]
Yes, this seems possible, but be aware that you'll probably need to hide the pages index from your users (permissions etc.). Maybe create a custom dashboard that links to their page resource editor?
